asdf

diff --git a/pkgs/scripts/.local/bin/scripts/arch/pman b/pkgs/scripts/.local/bin/scripts/arch/pman
--- a/pkgs/scripts/.local/bin/scripts/arch/pman
+++ b/pkgs/scripts/.local/bin/scripts/arch/pman
@@ -16,6 +16,27 @@
 # along with this program; if not, see
 # <https://www.gnu.org/licenses/>.
 
+say() {
+	_pre=$'\e[1m'
+	_post=$'\e[0m'
+	if [ $1 = "--err" ] ; then
+		_pre=$'\e[1;31m'
+		shift 1
+		echo "$_pre[pman] ${@:1}$_post" >&2
+	elif [ $1 = "--warn" ] ; then
+		_pre=$'\e[1;33m'
+		shift 1
+		echo "$_pre[pman] ${@:1}$_post" >&2
+	else
+		echo "$_pre[pman] ${@:1}$_post"
+	fi
+}
+ensure_cmd () {
+	if ! command -v $1 >/dev/null ; then
+		say --err "Command \`$1\` is not available"
+		exit 1
+	fi
+}
 
 # check if doas/sudo
 if command -v doas >/dev/null && [ -f /etc/doas.conf ] 2>&1 ; then
@@ -23,7 +44,7 @@ if command -v doas >/dev/null && [ -f /etc/doas.conf ] 2>&1 ; then
 elif command -v sudo >/dev/null ; then
 	SUCMD=sudo
 else
-	echo -e "\e[1;93m[pman]\e[0m Warning! Neither 'sudo' nor 'doas' is available." >&2
+	say --err "Warning! Neither 'sudo' nor 'doas' is available."
 fi
 
 help_str="Usage: pman SUBCOMMAND [ARGUMENTS] [PACMAN-OPTIONS]
@@ -65,52 +86,53 @@ if test $1 ; then
 		u | up | update )  $SUCMD pacman -Syu           ${@:2}  ;;
 		r | re | remove )  $SUCMD pacman -Rns --confirm ${@:2}  ;;
 		f | fi | find )
-			echo "Finding in remote repos..."
+			say "Finding in remote repos..."
 			pacman -Ss            ${@:2}
 			;;
 		fx | fix | fex | find-exact )
 			IFS='|'
-			echo "Finding ${@} in remote repos..."
+			say "Finding ${@} in remote repos..."
 			pacman -Ss "^(${*:2})$"
 			;;
 		s | se | search )
-			echo "Searching $2 in local database..."
+			say "Searching $2 in local database..."
 			pacman -Qs $2
 			;;
 		sx | sex | search-exact )
-			echo "Searching for ${@:2} in local database..."
+			say "Searching for ${@:2} in local database..."
 			pacman -Q ${@:2}
 			;;
 		info )
 			if [ -n "$3" ]; then
-				echo -e "\e[1;33m[pman]\e[0m Only one package name supported by \`pman info\`, ignoring the rest..." >&2
+				say --err "Only one package name supported by \`pman info\`, ignoring the rest..."
 			fi
 			pacman -Qii $2
 			if [ $? -ne 0 ]; then
-				echo -e "\e[1;33m[pman]\e[0m \`$2\` not found in local database. Trying again with command \`$(basename $0) info-remote\`" >&2
+				say --err "\`$2\` not found in local database. Trying again with command \`$(basename $0) info-remote\`"
 				pman info-remote $2
 			fi
 			;;
 		ir | infore | info-remote )
 			if [ -n "$3" ]; then
-				echo -e "\e[1;33m[pman]\e[0m Only one package name supported by \`pman info-remote\`, ignoring the rest..." >&2
+				say --warn "Only one package name supported by \`pman info-remote\`, ignoring the rest..." >&2
 			fi
 			pacman -Sii $2
 			if [ $? -ne 0 ]; then
-				echo -e "\e[1;31m[pman]\e[0m Could not find $2, try \`$(basename $0) refresh && $(basename $0) info $2\`" >&2
+				say --err "Could not find $2, try \`$(basename $0) refresh && $(basename $0) info $2\`" >&2
 				exit 1
 			fi
 			;;
 		autoremove )
 			TARGETS="$(pacman -Qdttnq)"
 			if [ -z "$TARGETS" ] ; then
-				echo -e "\e[1;32m[pman]\e[0m Nothing to remove";
+				say "Nothing to remove"
 			else
 				echo "$TARGETS" | $SUCMD pacman -Rns --confirm -
 			fi
 			;;
 		refresh) $SUCMD pacman -Sy ;;
 		update-mirrors)
+			ensure_cmd reflector
 			$SUCMD reflector --latest 20 \
 							  --sort rate \
 							  --country ${2:-'US,CO,'} \
@@ -124,6 +146,11 @@ if test $1 ; then
 			;;
 		provides) pacman -F  ${@:2} ;;
 		owns)     pacman -Qo ${@:2} ;;
+		file-tree)
+			ensure_cmd tree
+			pacman -Fl ${@:2} | tree --fromfile
+			;;
+		file-list) pacman -Fl ${@:2} ;;
 		* )
 			echo "$help_str"
 			exit 1
